const Model = require('objection').Model;
const uuid = require('uuid');

class BaseModel extends Model {
    $beforeInsert(context) {
        const parent = super.$beforeInsert(context);

        return Promise.resolve(parent)
            .then(() => {
                if (this.autoGeneratedId && !this[this.autoGeneratedId()]) {
                    this[this.autoGeneratedId()] = uuid.v4();
                }
            });
    }
}

module.exports = BaseModel;
