const BaseModel = require('./baseModel');
const Manufacturer = require('./manufacturer');
const PhoneModel = require('./phoneModel');

class Family extends BaseModel {
    static get tableName() {
        return 'families';
    }

    static get relationMappings() {
        return {
            manufacturer: {
                relation: BaseModel.BelongsToOneRelation,
                modelClass: Manufacturer,
                join: {
                    from: 'families.manufacturer',
                    to: 'manufacturers.id'
                }
            },
            models: {
                relation: BaseModel.HasManyRelation,
                modelClass: PhoneModel,
                join: {
                    from: 'families.id',
                    to: 'models.family'
                }
            }
        };
    }

    autoGeneratedId() {
        return 'id';
    }

    static get jsonSchema() {
        return {
            type: 'Object',
            properties: {
                id: { type: 'string' },
                manufacturer: { type: 'string' },
                name: { type: 'string' },
                config: { type: 'string' }
            }
        };
    }
}

module.exports = Family;
