const BaseModel = require('./baseModel');
const Family = require('./family');

class Manufacturer extends BaseModel {
    static get tableName() {
        return 'manufacturers';
    }

    static get relationMappings() {
        return {
            families: {
                relation: BaseModel.HasManyRelation,
                modelClass: Family,
                join: {
                    from: 'manufacturers.id',
                    to: 'families.manufacturer'
                }
            }
        };
    }

    autoGeneratedId() {
        return 'id';
    }

    static get jsonSchema() {
        return {
            type: 'Object',
            properties: {
                id: { type: 'string' },
                name: { type: 'string' },
                config: { type: 'string' }
            }
        };
    }
}

module.exports = Manufacturer;
