const BaseModel = require('./baseModel');
const Family = require('./family');

class PhoneModel extends BaseModel {
    static get tableName() {
        return 'models';
    }

    static get relationMappings() {
        return {
            family: {
                relation: BaseModel.BelongsToOneRelation,
                modelClass: Family,
                join: {
                    from: 'models.family',
                    to: 'families.id'
                }
            }
        };
    }

    autoGeneratedId() {
        return 'id';
    }

    static get jsonSchema() {
        return {
            type: 'Object',
            properties: {
                id: { type: 'string' },
                family: { type: 'string' },
                name: { type: 'string' },
                config: { type: 'string' }
            }
        };
    }
}

module.exports = PhoneModel;
