import {BaseModel} from 'db-starter';
import {Relation} from 'objection';
import {Manufacturer} from './manufacturer';
import {PhoneModel} from './phoneModel';

export class Family extends BaseModel {
    id: string;
    manufacturer: string;
    name: string;
    config: string;
    component_name: string;

    static get tableName() {
        return 'families';
    }

    autoGeneratedId() {
        return 'id';
    }
}