import {BaseModel} from 'reperio-db-starter';
import {Relation} from 'objection';
import {Family} from './family';

export class Manufacturer extends BaseModel {
    id: string;
    name: string;
    config: string;
    component_name: string;

    static get tableName() {
        return 'manufacturers';
    }

    autoGeneratedId() {
        return 'id';
    }
}