import {BaseModel} from 'reperio-db-starter';

export class Manufacturer extends BaseModel {
    id: string;
    name: string;
    component_name: string;

    static get tableName() {
        return 'manufacturers';
    }

    autoGeneratedId() {
        return 'id';
    }
}