import {BaseModel} from 'reperio-db-starter';

export class PhoneModel extends BaseModel {
    id: string;
    family: string;
    name: string;
    component_name: string;

    static get tableName() {
        return 'models';
    }

    autoGeneratedId() {
        return 'id';
    }
}